"""turn-off relationships for now

Revision ID: 022632b042d0
Revises: 2183f5cc08a9
Create Date: 2021-10-13 13:29:53.287066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022632b042d0'
down_revision = '2183f5cc08a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CommentSummaryXAuthor', sa.Column('commentSummaryId', sa.Integer(), nullable=True))
    op.drop_constraint('CommentSummaryXAuthor_commentSumamryId_fkey', 'CommentSummaryXAuthor', type_='foreignkey')
    op.create_foreign_key(None, 'CommentSummaryXAuthor', 'comment_summaries', ['commentSummaryId'], ['id'])
    op.drop_column('CommentSummaryXAuthor', 'commentSumamryId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CommentSummaryXAuthor', sa.Column('commentSumamryId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'CommentSummaryXAuthor', type_='foreignkey')
    op.create_foreign_key('CommentSummaryXAuthor_commentSumamryId_fkey', 'CommentSummaryXAuthor', 'comment_summaries', ['commentSumamryId'], ['id'])
    op.drop_column('CommentSummaryXAuthor', 'commentSummaryId')
    # ### end Alembic commands ###
