"""Default time fix

Revision ID: 0673a7b8f706
Revises: b9fde45e3ff8
Create Date: 2022-03-08 23:38:05.235880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0673a7b8f706'
down_revision = 'b9fde45e3ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
