"""add author, comment, comment-summary models

Revision ID: 2183f5cc08a9
Revises: 8096f0ba8790
Create Date: 2021-10-13 12:48:26.994855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2183f5cc08a9'
down_revision = '8096f0ba8790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('commented_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issues',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo', 'issue_number', name='repo_issue_number')
    )
    op.create_table('comment_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('issue', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['issue'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CommentSummaryXAuthor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commentSumamryId', sa.Integer(), nullable=True),
    sa.Column('authorId', sa.String(), nullable=True),
    sa.Column('edit', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['authorId'], ['authors.user_id'], ),
    sa.ForeignKeyConstraint(['commentSumamryId'], ['comment_summaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CommentSummaryXComment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commentSummaryId', sa.Integer(), nullable=True),
    sa.Column('commentId', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['commentId'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['commentSummaryId'], ['comment_summaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CommentSummaryXComment')
    op.drop_table('CommentSummaryXAuthor')
    op.drop_table('comment_summaries')
    op.drop_table('issues')
    op.drop_table('comments')
    op.drop_table('authors')
    # ### end Alembic commands ###
