"""relationship on only through comment summary

Revision ID: 39bd08be9e96
Revises: a3e79ecae952
Create Date: 2021-10-13 15:28:21.831144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39bd08be9e96'
down_revision = 'a3e79ecae952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
