"""Add TopLevelSummary and TopLevelSummarySpan

Revision ID: 58688c02bace
Revises: a50274628812
Create Date: 2022-03-07 21:25:22.313485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58688c02bace'
down_revision = 'a50274628812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TopLevelSummary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('info_type', sa.String(), nullable=False),
    sa.Column('issue', sa.String(), nullable=False),
    sa.Column('posted_on', sa.DateTime(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['issue'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue', 'info_type', name='issue_info_type')
    )
    op.create_index(op.f('ix_TopLevelSummary_issue'), 'TopLevelSummary', ['issue'], unique=False)
    op.create_table('TopLevelSummarySpan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('summary_span_start', sa.Integer(), nullable=False),
    sa.Column('summary_span_end', sa.Integer(), nullable=False),
    sa.Column('comment_span_start', sa.Integer(), nullable=False),
    sa.Column('comment_span_end', sa.Integer(), nullable=False),
    sa.Column('commented_on', sa.DateTime(), nullable=True),
    sa.Column('comment_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['TopLevelSummary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TopLevelSummarySpan_summary_id'), 'TopLevelSummarySpan', ['summary_id'], unique=False)
    op.alter_column('CommentInformationType', 'comment_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('CommentInformationType', 'comment_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_TopLevelSummarySpan_summary_id'), table_name='TopLevelSummarySpan')
    op.drop_table('TopLevelSummarySpan')
    op.drop_index(op.f('ix_TopLevelSummary_issue'), table_name='TopLevelSummary')
    op.drop_table('TopLevelSummary')
    # ### end Alembic commands ###
