"""Remove unnecessary foreign key constraints

Revision ID: 8542939d1a14
Revises: 58688c02bace
Create Date: 2022-03-08 20:08:27.545271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8542939d1a14'
down_revision = '58688c02bace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('TopLevelSummary_issue_fkey', 'TopLevelSummary', type_='foreignkey')
    op.drop_constraint('TopLevelSummarySpan_summary_id_fkey', 'TopLevelSummarySpan', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('TopLevelSummarySpan_summary_id_fkey', 'TopLevelSummarySpan', 'TopLevelSummary', ['summary_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('TopLevelSummary_issue_fkey', 'TopLevelSummary', 'issues', ['issue'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
