"""Add comment information type

Revision ID: a50274628812
Revises: b6db0f24b0f5
Create Date: 2022-01-05 17:18:11.342308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50274628812'
down_revision = 'b6db0f24b0f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CommentInformationType',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment_id', sa.String(), nullable=True),
    sa.Column('issue', sa.String(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('span_start', sa.Integer(), nullable=False),
    sa.Column('span_end', sa.Integer(), nullable=False),
    sa.Column('info_type', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CommentInformationType_issue'), 'CommentInformationType', ['issue'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_CommentInformationType_issue'), table_name='CommentInformationType')
    op.drop_table('CommentInformationType')
    # ### end Alembic commands ###
