"""cascade added on relationships

Revision ID: b6db0f24b0f5
Revises: e95932a8d68a
Create Date: 2021-10-14 22:23:02.524140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6db0f24b0f5'
down_revision = 'e95932a8d68a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('CommentSummaryXAuthor_commentSummaryId_fkey', 'CommentSummaryXAuthor', type_='foreignkey')
    op.create_foreign_key(None, 'CommentSummaryXAuthor', 'comment_summaries', ['commentSummaryId'], ['id'], ondelete='CASCADE')
    op.drop_constraint('CommentSummaryXComment_commentSummaryId_fkey', 'CommentSummaryXComment', type_='foreignkey')
    op.create_foreign_key(None, 'CommentSummaryXComment', 'comment_summaries', ['commentSummaryId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'CommentSummaryXComment', type_='foreignkey')
    op.create_foreign_key('CommentSummaryXComment_commentSummaryId_fkey', 'CommentSummaryXComment', 'comment_summaries', ['commentSummaryId'], ['id'])
    op.drop_constraint(None, 'CommentSummaryXAuthor', type_='foreignkey')
    op.create_foreign_key('CommentSummaryXAuthor_commentSummaryId_fkey', 'CommentSummaryXAuthor', 'comment_summaries', ['commentSummaryId'], ['id'])
    # ### end Alembic commands ###
