"""relationship based on orm classes

Revision ID: e95932a8d68a
Revises: 39bd08be9e96
Create Date: 2021-10-14 21:52:01.177541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95932a8d68a'
down_revision = '39bd08be9e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
